from django.core.management.base import BaseCommand
from cars.models import Car

class Command(BaseCommand):
    help = 'Seed 18 cars into the database'

    def handle(self, *args, **kwargs):
        Car.objects.all().delete()
        self.stdout.write('Deleted existing cars...')

        cars = [
            dict(name='Mercedes GLE', brand='Mercedes', model='GLE', year=2023, price=28000000, category='suv', condition='new', mileage=0, fuel_type='petrol', transmission='automatic', color='Black', features=['V6 Engine', 'Panoramic Roof', 'Air Suspension'], specs={'engine': 'V6', 'horsepower': 367, 'torque': '500 Nm', 'top_speed': '250 km/h', 'acceleration': '5.6s', 'drivetrain': 'AWD'}, in_stock=True, is_featured=True),
            dict(name='Mercedes AMG C63', brand='Mercedes', model='AMG C63', year=2022, price=32000000, category='sports', condition='new', mileage=0, fuel_type='petrol', transmission='automatic', color='White', features=['V8 Engine', 'AMG Track Pace', 'Launch Control'], specs={'engine': 'V8', 'horsepower': 503, 'torque': '700 Nm', 'top_speed': '290 km/h', 'acceleration': '3.9s', 'drivetrain': 'RWD'}, in_stock=True, is_featured=True),
            dict(name='Mercedes SL 500', brand='Mercedes', model='SL 500', year=2021, price=25000000, category='luxury', condition='new', mileage=0, fuel_type='petrol', transmission='automatic', color='Silver', features=['V8 Engine', 'Retractable Roof', 'Burmester Sound'], specs={'engine': 'V8', 'horsepower': 449, 'torque': '700 Nm', 'top_speed': '275 km/h', 'acceleration': '4.3s', 'drivetrain': 'RWD'}, in_stock=True, is_featured=False),
            dict(name='Mercedes AMG GT', brand='Mercedes', model='AMG GT', year=2023, price=45000000, category='sports', condition='new', mileage=0, fuel_type='petrol', transmission='automatic', color='Red', features=['V8 Biturbo', 'AMG Ride Control', 'Carbon Fiber'], specs={'engine': 'V8 Biturbo', 'horsepower': 577, 'torque': '730 Nm', 'top_speed': '315 km/h', 'acceleration': '3.5s', 'drivetrain': 'RWD'}, in_stock=True, is_featured=True),
            dict(name='Mercedes E-Class', brand='Mercedes', model='E-Class', year=2022, price=18000000, category='luxury', condition='new', mileage=0, fuel_type='petrol', transmission='automatic', color='Black', features=['I6 Engine', 'MBUX System', 'Widescreen Display'], specs={'engine': 'I6', 'horsepower': 255, 'torque': '400 Nm', 'top_speed': '250 km/h', 'acceleration': '6.0s', 'drivetrain': 'RWD'}, in_stock=True, is_featured=False),
            dict(name='Mercedes CLA', brand='Mercedes', model='CLA', year=2021, price=12000000, category='luxury', condition='used', mileage=15000, fuel_type='petrol', transmission='automatic', color='Gray', features=['I4 Engine', 'MBUX Infotainment', 'LED Headlights'], specs={'engine': 'I4', 'horsepower': 221, 'torque': '350 Nm', 'top_speed': '240 km/h', 'acceleration': '6.8s', 'drivetrain': 'FWD'}, in_stock=False, is_featured=False),
            dict(name='Honda Civic Type R', brand='Honda', model='Civic Type R', year=2023, price=8500000, category='sports', condition='new', mileage=0, fuel_type='petrol', transmission='manual', color='Championship White', features=['Turbo Engine', 'Brembo Brakes', 'Adaptive Dampers'], specs={'engine': 'I4 Turbo', 'horsepower': 315, 'torque': '420 Nm', 'top_speed': '272 km/h', 'acceleration': '5.4s', 'drivetrain': 'FWD'}, in_stock=True, is_featured=True),
            dict(name='Honda Accord', brand='Honda', model='Accord', year=2022, price=7000000, category='luxury', condition='new', mileage=0, fuel_type='hybrid', transmission='automatic', color='Platinum White', features=['Hybrid Engine', 'Honda Sensing', 'Wireless CarPlay'], specs={'engine': 'I4 Hybrid', 'horsepower': 192, 'torque': '315 Nm', 'top_speed': '200 km/h', 'acceleration': '7.8s', 'drivetrain': 'FWD'}, in_stock=True, is_featured=False),
            dict(name='Honda Civic SI', brand='Honda', model='Civic SI', year=2021, price=5500000, category='sports', condition='used', mileage=12000, fuel_type='petrol', transmission='manual', color='Boost Blue', features=['Sport Suspension', 'Limited Slip Diff', 'Rev Match'], specs={'engine': 'I4', 'horsepower': 200, 'torque': '260 Nm', 'top_speed': '225 km/h', 'acceleration': '6.5s', 'drivetrain': 'FWD'}, in_stock=True, is_featured=False),
            dict(name='Tesla Model 3', brand='Tesla', model='Model 3', year=2023, price=15000000, category='electric', condition='new', mileage=0, fuel_type='electric', transmission='automatic', color='Midnight Silver', features=['Autopilot', '15" Touchscreen', 'OTA Updates'], specs={'engine': 'Dual Motor', 'horsepower': 358, 'torque': '493 Nm', 'top_speed': '233 km/h', 'acceleration': '4.2s', 'drivetrain': 'AWD'}, in_stock=True, is_featured=True),
            dict(name='Tesla Model S', brand='Tesla', model='Model S', year=2023, price=28000000, category='electric', condition='new', mileage=0, fuel_type='electric', transmission='automatic', color='Pearl White', features=['Plaid Mode', '17" Cinematic Display', 'Full Self Driving'], specs={'engine': 'Tri Motor', 'horsepower': 1020, 'torque': '1420 Nm', 'top_speed': '322 km/h', 'acceleration': '1.99s', 'drivetrain': 'AWD'}, in_stock=True, is_featured=True),
            dict(name='Tesla Model X', brand='Tesla', model='Model X', year=2022, price=32000000, category='electric', condition='used', mileage=8000, fuel_type='electric', transmission='automatic', color='Deep Blue', features=['Falcon Wing Doors', '7-Seater', 'Bioweapon Defense Mode'], specs={'engine': 'Dual Motor', 'horsepower': 670, 'torque': '900 Nm', 'top_speed': '250 km/h', 'acceleration': '3.9s', 'drivetrain': 'AWD'}, in_stock=False, is_featured=False),
            dict(name='Aston Martin DB11', brand='Aston Martin', model='DB11', year=2022, price=65000000, category='luxury', condition='new', mileage=0, fuel_type='petrol', transmission='automatic', color='Onyx Black', features=['V12 Engine', 'Aeroblade', 'Hand-Stitched Interior'], specs={'engine': 'V12', 'horsepower': 608, 'torque': '700 Nm', 'top_speed': '301 km/h', 'acceleration': '3.7s', 'drivetrain': 'RWD'}, in_stock=True, is_featured=True),
            dict(name='Aston Martin Vantage', brand='Aston Martin', model='Vantage', year=2023, price=55000000, category='sports', condition='new', mileage=0, fuel_type='petrol', transmission='automatic', color='Lime Essence', features=['V8 Twin Turbo', 'Adaptive Damping', 'Sport Plus Seats'], specs={'engine': 'V8 Twin Turbo', 'horsepower': 503, 'torque': '625 Nm', 'top_speed': '314 km/h', 'acceleration': '3.6s', 'drivetrain': 'RWD'}, in_stock=True, is_featured=True),
            dict(name='Aston Martin DBX', brand='Aston Martin', model='DBX', year=2023, price=58000000, category='suv', condition='new', mileage=0, fuel_type='petrol', transmission='automatic', color='Magnetic Silver', features=['V8 Engine', 'Air Suspension', 'Terrain Management'], specs={'engine': 'V8', 'horsepower': 542, 'torque': '700 Nm', 'top_speed': '291 km/h', 'acceleration': '4.3s', 'drivetrain': 'AWD'}, in_stock=True, is_featured=False),
            dict(name='Classic Mustang', brand='Ford', model='Mustang', year=1969, price=9000000, category='classic', condition='used', mileage=45000, fuel_type='petrol', transmission='manual', color='Candy Apple Red', features=['V8 Engine', 'Restored Interior', 'Numbers Matching'], specs={'engine': 'V8', 'horsepower': 320, 'torque': '475 Nm', 'top_speed': '200 km/h', 'acceleration': '6.5s', 'drivetrain': 'RWD'}, in_stock=True, is_featured=False),
            dict(name='Classic Porsche 911', brand='Porsche', model='911', year=1974, price=14000000, category='classic', condition='used', mileage=62000, fuel_type='petrol', transmission='manual', color='Gulf Orange', features=['Flat-6 Engine', 'Original Paint', 'Full Service History'], specs={'engine': 'Flat-6', 'horsepower': 210, 'torque': '255 Nm', 'top_speed': '230 km/h', 'acceleration': '7.0s', 'drivetrain': 'RWD'}, in_stock=True, is_featured=False),
            dict(name='Classic Jaguar E-Type', brand='Jaguar', model='E-Type', year=1968, price=18000000, category='classic', condition='used', mileage=55000, fuel_type='petrol', transmission='manual', color='British Racing Green', features=['I6 Engine', 'Fully Restored', 'Matching Numbers'], specs={'engine': 'I6', 'horsepower': 265, 'torque': '352 Nm', 'top_speed': '240 km/h', 'acceleration': '7.0s', 'drivetrain': 'RWD'}, in_stock=False, is_featured=False),
        ]

        for car_data in cars:
            Car.objects.create(**car_data)
            self.stdout.write(f"  ✅ Added: {car_data['name']}")

        self.stdout.write(self.style.SUCCESS(f'\n🎉 Done! {len(cars)} cars added successfully.'))